apiVersion: v1
kind: ServiceAccount
metadata:
  name: fs4 # Modify this line with the service name
---
apiVersion: v1
kind: Service
metadata:
  name: fs4 # Modify this line with the service name
  labels:
    app: fs4 # Modify this line with the service name
    service: fs4 # Modify this line with the service name
spec:
  ports:
  - port: 84 # Modify this line with the listening port
    name: http
  selector:
    app: fs4 # Modify this line with the service name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs4 # Modify this line with the service name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs4 # Modify this line with the service name
  template:
    metadata:
      labels:
        app: fs4 # Modify this line with the service name
    spec:
      #nodeSelector:
      #  appName: fs4
      terminationGracePeriodSeconds: 0
      serviceAccountName: fs4 # Modify this line with the service name
      containers:
      - name: fake-service4 # Modify this line with the service name
        image: nicholasjackson/fake-service:v0.24.2
        imagePullPolicy: IfNotPresent
        env:
          - name: NAME
            value: "fs4" # Modify this line with the service name
          - name: LISTEN_ADDR
            value: "0.0.0.0:84" # Modify this line with the service name
          - name: MESSAGE
            value: "Fake Service -- 4" # Modify this line with the service name
          - name: HTTP_CLIENT_APPEND_REQUEST
            value: "false"
          - name: UPSTREAM_URIS
            value: "http://fs5:85"
