apiVersion: v1
kind: ServiceAccount
metadata:
  name: fs5 # Modify this line with the service name
---
apiVersion: v1
kind: Service
metadata:
  name: fs5 # Modify this line with the service name
  labels:
    app: fs5 # Modify this line with the service name
    service: fs5 # Modify this line with the service name
spec:
  ports:
  - port: 85 # Modify this line with the listening port
    name: http
  selector:
    app: fs5 # Modify this line with the service name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs5 # Modify this line with the service name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs5 # Modify this line with the service name
  template:
    metadata:
      labels:
        app: fs5 # Modify this line with the service name
    spec:
      nodeSelector:
        appName: fs5
      terminationGracePeriodSeconds: 0
      serviceAccountName: fs5 # Modify this line with the service name
      containers:
      - name: fake-service5 # Modify this line with the service name
        image: nicholasjackson/fake-service:v0.24.2
        imagePullPolicy: IfNotPresent
        env:
          - name: NAME
            value: "fs5" # Modify this line with the service name
          - name: LISTEN_ADDR
            value: "0.0.0.0:85" # Modify this line with the service name
          - name: MESSAGE
            value: "Fake Service -- 5" # Modify this line with the service name
          - name: HTTP_CLIENT_APPEND_REQUEST
            value: "false"
              #          - name: UPSTREAM_URIS
              #            value: ""
      - name: etcd
        image: bitnami/etcd
        imagePullPolicy: IfNotPresent
        env:
          - name: ALLOW_NONE_AUTHENTICATION
            value: "yes"
          - name: ETCD_LISTEN_CLIENT_URLS
            value: "http://0.0.0.0:2379"
        ports:
        - containerPort: 2379
        - containerPort: 2380

